script perso

diff --git a/scripts/03 b/scripts/03
--- a/scripts/03
+++ b/scripts/03
@@ -1,3 +1,60 @@
 #!/bin/bash
-sudo apt-get update
-sudo apt-get upgrade
+
+while :
+do
+ clear
+ echo " -----------------------------------------------------------"
+ echo "| 1.Preset-Packages 3.Update-Packages 5.Fast-Git-Push |\n
+       | 2.Install-Packages 4.Upgrade-Packages 6.Exit |" | column -t
+ echo " -----------------------------------------------------------\n"
+ read INPUT
+ case $INPUT in
+ 	1)
+		echo "The following packages will be installed :"
+		echo "gcc\nvim\nmake\ngit\nemacs\n"
+		sleep 1
+		sudo apt-get install gcc vim make git emacs
+		;;
+	2)
+		echo "\nName of the package"
+		read PACK
+		sudo apt-get install $PACK;;
+	3)
+		sudo apt-get update;;
+	4)
+		sudo apt-get upgrade;;
+	5)
+		git add *
+		git status
+		if [ $? -eq 0 ];then
+			echo "Write the commit message :"
+			read MSG
+			git commit -m "$MSG"
+			if [ $? -eq 0 ];then
+				echo "\n\nSUCCESS"
+				git push
+				if [ $? -eq 0 ];then
+					echo "\n\nSUCCESS"
+				else
+					echo "\n\nERROR : You can't do that\n\n"
+					echo "Press Enter to continue"
+					read INPUT
+				fi
+			else
+				echo "\n\nERROR : You can't do that\n\n"
+				echo "Press Enter to continue"
+				read INPUT
+			fi
+		else
+			echo "\n\nERROR : You can't do that\n\n"
+			echo "Press Enter to continue"
+			read INPUT
+		fi;;
+	6)
+		break ;;
+	*)
+		echo "\n$INPUT is not a valid option";;
+ esac
+ sleep 1.5
+done
+clear
